### ISSUE TITLE
Add Search

### ISSUE THREAD

**Issue by webit-richardkramer** [josh-gaby/2fauth-browser-extension#15]
Would it be possible to add add a search option for finding the correct account? 

I really love the easy access to my tokens, but find myself constantly scrolling and searching for keys, that are a but further down. A searchbar, instantly focused when opening the extension window, would improve this drastically.

**Comment by josh-gaby** [comment]
Great idea, I'll start implementing one.

**Comment by josh-gaby** [comment]
I've added a search bar to the accounts page, the new version has been submitted to both the Chrome and Firefox webstores and should be available in the next few of days, although Google can take longer.

**Comment by webit-richardkramer** [comment]
Thank you, that was really fast. The update already propagated to my browser extension and works great.
