### ISSUE TITLE
Autofocus search bar after unlocking

### ISSUE THREAD

**Issue by richard-kramer** [josh-gaby/2fauth-browser-extension#17]
Because I have quite a few accounts saved in my 2FAuth, I'm using the search bar implemented in #16 quite a lot.

I also use the extension with a password. Unfortunately, after entering the password, the search bar is not autofocused, unlike after opening the already unlocked extension window. This requires an additional click, I find a tiny bit annoying.

Would it be possible to also autofocus the search bar after entering the password?

**Comment by josh-gaby** [comment]
Makes sense, I'll add it for the next release. I don't have a time frame on that at this stage though.
