### ISSUE TITLE
Release the Addon and sign it

### ISSUE THREAD

**Issue by BLACK4585** [josh-gaby/2fauth-browser-extension#9]
Simply what the title says. It's currently only working on Firefox if you load it as a temporary add-on, which is not very useful because you have to re-enable it on every browser restart.
Thank you!

**Comment by josh-gaby** [comment]
I did add it to the Mozilla addon hub in May of 2023, although it looks like I had flagged it for `self` hosting making it not visible in the addon store.

I've just resubmitted a new version, it should be available here [https://addons.mozilla.org/en-GB/firefox/addon/2fauth/](https://addons.mozilla.org/en-GB/firefox/addon/2fauth/) once the update has been reviewed.

**Comment by josh-gaby** [comment]
The extension is now available in both the Firefox and Chrome webstores and the README has been updated with links to both.

**Comment by BLACK4585** [comment]
Nice thank you!
